# Generated by Django 5.1.3 on 2024-11-09 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="likes",
        ),
    ]
